### ISSUE TITLE
dbURL2 help please

### ISSUE THREAD

**Issue by TheTeaCup** [fatchan/discord-bot-website#2]
Hi, im new to Mongo
`app.use(session({
    secret: config.sessionSecret,
    store: new MongoStore({ url: config.dbURL2 }),
    resave: false,
    saveUninitialized: false
}));` 
 and i cant get it to work correctly 
i have my dbURL2 set to koala.glitch.me/storage but it doesnt work can someone on help me?

**Comment by TheTeaCup** [comment]
i have changed my dbURL2 to koala.glitch.me and it works but then times out

**Comment by fatchan** [comment]
should be your mongodb url string mongodb://username:password@host:post/databasename
